add warning messages

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,4 +1,11 @@
 #!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
+. "$(dirname $0)/_/husky.sh"
+
+set +e
 
 npx --no-install commitlint --edit $1
+if [ $? -ne 0 ]; then
+  echo "WARNING: failed to run commit message validation (npx --no-install commitlint)"
+fi
+
+exit 0;
diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,10 @@
 #!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
+. "$(dirname $0)/_/husky.sh"
 
+set +e
 npx pretty-quick --staged
+if [ $? -ne 0 ]; then
+  echo "WARNING: failed to run file formatting (npx pretty-quick --staged)"
+fi
+
+exit 0;
